AllCops:
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'bin/*'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
Metrics/LineLength:
  Enabled: false
