language: ruby
rvm:
  - 2.5.1
before_install:
  - gem install bundler -v '1.17.3'
  - bundle install --without development
  - rails yarn:install
script:
  - rails db:create db:migrate
  - rails webpacker:compile
  - rails test
notifications:
  slack: getnoodles:EQiFyZq4M1Tv94DaXRN8f2Gy
