language: ruby
rvm:
  - 2.2.3
before_install:
  - gem install bundler
  - bundle install --without development
script:
  - rake db:create db:migrate
notifications:
  slack: getnoodles:EQiFyZq4M1Tv94DaXRN8f2Gy
