language: ruby
services:
  - postgresql
rvm:
  - 2.7.2
before_script:
  - psql -c 'create database noodles_test;' -U postgres
before_install:
  - gem install bundler -v '2.1.4'
  - bundle install --without development
  - rails yarn:install
script:
  - rails db:create db:migrate
  - rails webpacker:compile
  - rails test
notifications:
  slack: getnoodles:EQiFyZq4M1Tv94DaXRN8f2Gy
