source 'https://rubygems.org'
ruby '2.2.3'

gem 'dotenv-rails', groups: [:development, :test]

gem 'rails_autolink'
gem 'ahoy_matey'
gem 'autoprefixer-rails'
gem 'aws-sdk', '< 2.0'
gem 'devise'
gem 'devise_marketable'
gem 'coffee-rails'
gem 'cohort_me'
gem 'fastimage'
gem 'hangry'
gem 'ingreedy'
gem 'intercom-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mandrill_dm'
gem 'mechanize'
gem 'newrelic_rpm'
gem 'paperclip'
gem 'pg'
gem 'prawnto_2', require: 'prawnto'
gem 'premailer-rails'
gem 'puma'
gem 'rails', '4.2.4'
gem 'rake'
gem 'react-rails'
gem 'redcarpet'
gem 'rmagick'
gem 'safely_block'
gem 'sass-rails'
gem 'slowpoke'
gem 'uglifier'
gem 'wombat'
gem 'zeroclipboard-rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'seed_dump'
  gem 'tracer_bullets'
end

group :production do
  gem 'rails_12factor'
end
