export default [
  'All-purpose cleaner',
  'All-purpose flour',
  'Almond milk',
  'Aluminum foil',
  'Apples',
  'Arugala',
  'Asparagus',
  'Avocados',
  'Bagels',
  'Baking powder',
  'Baking soda',
  'Bananas',
  'Basil',
  'BBQ sauce',
  'Beans',
  'Beef',
  'Berries',
  'Biscuits',
  'Body wash',
  'Bottled water',
  'Bread flour',
  'Bread',
  'Breadcrumbs',
  'Broccoli',
  'Buns',
  'Butter',
  'Cake',
  'Canned tomatoes',
  'Canola oil',
  'Carrots',
  'Cat food',
  'Celery',
  'Cereal',
  'Cheese',
  'Chicken broth',
  'Chicken',
  'Chili powder',
  'Chips',
  'Chocolate',
  'Chorizo',
  'Cilantro',
  'Cleaning sponges',
  'Cleanser',
  'Clementines',
  'Cocoa',
  'Conditioner',
  'Cookies',
  'Corn',
  'Cottage cheese',
  'Crackers',
  'Cream cheese',
  'Cream',
  'Cucumber',
  'Deodorant',
  'Deodorant',
  'Diapers',
  'Dill',
  'Dish soap',
  'Dishwasher detergent',
  'Dishwasher soap',
  'Dishwashing liquid',
  'Disinfectant',
  'Dog food',
  'Donuts',
  'Donuts',
  'Eggs',
  'Fabric softener',
  'Fish',
  'Floor cleaner',
  'Flour',
  'Freezer bags',
  'Frozen vegetables',
  'Fruit',
  'Garbage bags',
  'Garlic powder',
  'Garlic',
  'Ginger',
  'Grapefruit',
  'Grapes',
  'Green beans',
  'Ground beef',
  'Half & half',
  'Hamburger buns',
  'Heavy cream',
  'Honey',
  'Hot cocoa',
  'Hot dogs',
  'Ice cream',
  'Jelly',
  'Jelly',
  'Juice',
  'Ketchup',
  'Laundry detergent',
  'Laundry soap',
  'Lemonade',
  'Lemons',
  'Lentils',
  'Lettuce',
  'Lettuce',
  'Light bulbs',
  'Limes',
  'Mangoes',
  'Maple syrup',
  'Mayonnaise',
  'Melons',
  'Milk',
  'Mouthwash',
  'Mushrooms',
  'Mustard',
  'Napkins',
  'Nectarines',
  'Olive oil',
  'Onions',
  'Orange juice',
  'Oranges',
  'Oregano',
  'Paper cups',
  'Paper plates',
  'Paper towels',
  'Paprika',
  'Parsley',
  'Pasta sauce',
  'Pasta',
  'Pastry flour',
  'Peaches',
  'Peanut butter',
  'Pears',
  'Pepper',
  'Pie',
  'Pie',
  'Pineapple',
  'Pita pockets',
  'Pizza',
  'Plastic wrap',
  'Plums',
  'Pork',
  'Potatoes',
  'Pretzels',
  'Pudding',
  'Radishes',
  'Relish',
  'Rice',
  'Ricotta',
  'Rolls',
  'Salad',
  'Salt',
  'Sandwich bags',
  'Sausage',
  'Shampoo',
  'Shaving cream',
  'Shredded cheese',
  'Shrimp',
  'Skim milk',
  'Snacks',
  'Soap',
  'Soda',
  'Sour cream',
  'Soy sauce',
  'Spinach',
  'Spinach',
  'Squash',
  'Steak sauce',
  'Strawberries',
  'Sugar',
  'Sunscreen',
  'Sweet treats',
  'Taco shells',
  'Tampons',
  'Tea',
  'Tissues',
  'Toilet paper',
  'Tomatoes',
  'Toothbrush',
  'Toothpaste',
  'Toothpicks',
  'Tortillas',
  'Turkey',
  'Vanilla extract',
  'Vegetable broth',
  'Vegetable oil',
  'Vegetables',
  'Vinegar',
  'Waffles',
  'Watermelon',
  'Wax paper',
  'White beans',
  'Whole milk',
  'Whole oats',
  'Whole wheat flour',
  'Window cleaner',
  'Worcestershire sauce',
  'Yeast',
  'Yogurt'
]
