version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These set the ARG values in your Dockerfile
        VARIANT: 2.7
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    network_mode: host

# Persist database information after your VM shuts down (just these two lines!)
volumes:
  postgres_data:
